---

name: Run Tests
on: push

defaults:
  run:
    shell: bash

jobs:
  empty:
    name: Empty Program
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Grawk
        uses: ./

  hello-world-from-inline-program:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: grawk
        name: Run Grawk
        uses: ./
        with:
          program: |
            BEGIN {
              print "Hello World!"
            }

      - name: Assert Output Is Correct
        run: test "${HAVE}" = "${WANT}"
        env:
          HAVE: ${{ steps.grawk.outputs.result }}
          WANT: "Hello World!"

  hello-world-from-program-file:
    name: Hello World (hello_world.awk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Script
        run: echo 'BEGIN { print "Hello World!" }' > hello_world.awk

      - id: grawk
        name: Run Grawk
        uses: ./
        with:
          program-file: hello_world.awk

      - name: Assert Output Is Correct
        run: test "${HAVE}" = "${WANT}"
        env:
          HAVE: ${{ steps.grawk.outputs.result }}
          WANT: "Hello World!"

  both-program-and-program-file:
    name: Both Program and Program File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Script
        run: echo 'BEGIN { print "PROGRAM_FILE" }' > script.awk

      - id: grawk
        name: Run Grawk
        uses: ./
        with:
          program-file: ./script.awk
          program: |
            BEGIN {
              print "PROGRAM"
            }

      - name: Assert Output Is Correct
        run: test "${HAVE}" = "${WANT}"
        env:
          HAVE: ${{ steps.grawk.outputs.result }}
          WANT: "PROGRAM_FILE\nPROGRAM"

  input-with-default-separator:
    name: Process Input With Default Separator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: grawk
        name: Run Grawk
        uses: ./
        with:
          input: "a,b,c, d,e,f, g,h,i,"
          program: "{ print $2 }"

      - name: Assert Output Is Correct
        run: test "${HAVE}" = "${WANT}"
        env:
          HAVE: ${{ steps.grawk.outputs.result }}
          WANT: "d,e,f,"

  input-with-given-separator:
    name: Process Input With Specified Separator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: grawk
        name: Run Grawk
        uses: ./
        with:
          separator: ","
          input: "a,b,c, d,e,f, g,h,i,"
          program: "{ print $2 }"

      - name: Assert Output Is Correct
        run: test "${HAVE}" = "${WANT}"
        env:
          HAVE: ${{ steps.grawk.outputs.result }}
          WANT: "b"

  input-from-file:
    name: Process Input From Given Filename
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: grawk
        name: Run Grawk
        uses: ./
        with:
          input-file: .github/testing/students.csv
          separator: ','
          program: |
            $1 == "Alex" {
              print $2 ", " $1 ": " $3 " year old " $4 " student"
            }

      - name: Assert Output Is Correct
        run: test "${HAVE}" = "${WANT}"
        env:
          HAVE: ${{ steps.grawk.outputs.result }}
          WANT: "Abrams, Alex: 21 year old Physics student"
